# Stage 1
FROM node:23 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . ./
RUN npm run build   # only if you have a build script

# Stage 2
FROM node:23 AS runtime
WORKDIR /app

COPY --from=builder /app /app
CMD ["npm", "start"]
